pretas = '○'
brancas = '●'
vazio = ' '
dama_preta = '◎'
dama_branca = '◉'
J1 = ''
J2 = ''
ress = ''
matriz=[]
jogador_atual = 0
quant_pecas_j1 = 12
quant_pecas_j2 = 12
quant_damas_j1 = 0
quant_damas_j2 = 0
obrigatorio_preta = []
obrigatorio_branca = []
quant_jogadas_con_j1 = 0
quant_jogadas_con_j2 = 0
quant_jogadas_j1 = 0
quant_jogadas_j2 = 0